// <auto-generated />
using System;
using DomainEntities.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DomainEntities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePayGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HierarchyLevel1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HierarchyLevel2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HireDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("DomainEntities.EmployeeUpdate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountManagerSupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountManagerSupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AccountUser")
                        .HasColumnType("bit");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Agency")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPunchFromPersonalDevice")
                        .HasColumnType("bit");

                    b.Property<string>("AssignedAccountUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BillRate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BiometricTrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClockPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplianceSupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplianceSupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DailyHours")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultHierarchyItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultHierarchyItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultJobId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultJobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultPhaseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultPhaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultPositionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultPunchHierarchyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<double>("DoubleTimeBillFactor")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerPrivacyAgreementAcknowledgedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinddPrivacyAgreementAcknowledgedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FullTime")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationHierarchyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OvertimeBillFactor")
                        .HasColumnType("float");

                    b.Property<string>("OvertimeRuleGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PasswordHashed")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PayRate")
                        .HasColumnType("float");

                    b.Property<string>("PayrollHierarchyItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollHierarchyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollSupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollSupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageS3Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterSupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterSupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePhase")
                        .HasColumnType("bit");

                    b.Property<string>("SSOToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleWeight")
                        .HasColumnType("int");

                    b.Property<string>("SelectedCandidateFilter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedPeopleFilter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedUserFilter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TicksSinceActivePropsChange")
                        .HasColumnType("bigint");

                    b.Property<long>("TicksSinceChange")
                        .HasColumnType("bigint");

                    b.Property<long>("TicksSinceInactivePropsChange")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserModified")
                        .HasColumnType("bit");

                    b.Property<string>("UserRoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WeeklyHours")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("employeeUpdatedFile");
                });

            modelBuilder.Entity("DomainEntities.HierarchyItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HierarchyDefinitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollExportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("UserModified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HierarchyItems");
                });

            modelBuilder.Entity("DomainEntities.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActiveUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("BasePositionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Copied")
                        .HasColumnType("bit");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HierarchyItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseActiveUntilDate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyItemId");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("EmployeeUpdatePosition", b =>
                {
                    b.Property<string>("PositionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("employeeUpdatesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PositionId", "employeeUpdatesId");

                    b.HasIndex("employeeUpdatesId");

                    b.ToTable("EmployeeUpdatePosition");
                });

            modelBuilder.Entity("DomainEntities.Position", b =>
                {
                    b.HasOne("DomainEntities.HierarchyItem", null)
                        .WithMany("Position")
                        .HasForeignKey("HierarchyItemId");
                });

            modelBuilder.Entity("EmployeeUpdatePosition", b =>
                {
                    b.HasOne("DomainEntities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainEntities.EmployeeUpdate", null)
                        .WithMany()
                        .HasForeignKey("employeeUpdatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainEntities.HierarchyItem", b =>
                {
                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
